### ISSUE TITLE
Add Cryptsy as a market

### ISSUE THREAD

**Issue by lottoicoind** [iquidus/explorer#12]
Hey guys,

you have done really great work. As a suggestion, please add cryptsy as a market.

cheers

**Comment by ssdpool** [comment]
hi Luke , I noticed him to add this as issue :), really is not issue , when have time if can add and cryptsy :)

**Comment by iquidus** [comment]
haha, I have been putting off cryptsy simply because i dont like its api and no one had requested it :P, but now that it has been requested it shall be done, expect to see it in the next update.

**Comment by lottoicoind** [comment]
hey Luke, glad to hear that you are going to work on it :D 
the good thing is, once a coin hits cryptsy it will not be romved, so for older coins that dont have a high volume on eg bittrex it would be great

**Comment by mammix2** [comment]
Not sure if this is an issue or the fact Cryptsy has been offline recent;y but i'm getting this error on the market page...

/home/administrator/bost-explorer/views/markets/cryptsy.jade:22 20| tbody 21| tr > 22| td #{marketdata.data.summary.high} 23| td #{marketdata.data.summary.low} 24| td #{marketdata.data.summary.volume} 25| td.hidden-xs #{marketdata.data.summary.bid} Cannot read property 'high' of null


The Cryptsy market ID is 297
https://www.cryptsy.com/markets/view/BOST_BTC

**Comment by rudy4682** [comment]
https://api.cryptsy.com/ 

api.cryptsy.com - Connection failed
Error code 20
The proxy failed to connect to the web server, due to TCP connection timeout.
2015-07-08 14:52:55 UTC
Your IP70.168.69.126|Proxy IP192.230.68.96(ID 1084)Origin Server IPX.X.X.243

Still offline

**Comment by iquidus** [comment]
I'd like to thank @rudy4682 for his recent additions to the explorer! nice work (saved me a lot of hassle). I ended up striping the cryptsy code down to just the one pairing for now, as I want to overhaul the markets code again so multiple pairings and market specific options can be done in a cleaner manner. Also had been meaning to add hashrate units option for a while but you beat me to it. much appreciated.  I'll test the Cryptsy code some more when I get a chance but I doubt the issue is on the explorer end (the code was good), although I will definitely clean up those errors in the next release.
