### ISSUE TITLE
How to set up Explorer Access at a Domain or Subdomain (without the port number)

### ISSUE THREAD

**Issue by CryptvJet** [iquidus/explorer#121]
Hi, I feel like I am missing something small here.

Unable to set the explorer on a subdomain.

I would like to access the explorer at sub.domain.com but am only able to access it at sub.domain.com:3001

The explorer works fine at sub.domain.com:3001

How can I set this explorer to my subdomain so that users dont have to remember the port number too?

Any help here would be appreciated.

Thanks,

**Comment by erfan007p** [comment]
Change port 3001 in settings.json to 80

**Comment by cryptoj** [comment]
@erfan007p 

Thank you for the input,

That might work if I have a server set up specifically for this one block explorer, but I have the explorer set up on a linux server with multiple websites.

Currently, since its installed on the server the explorer is available at all of the domains on port 3751

When I changed 3001 to 80 and ran npm I got the following error:

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: bind EADDRINUSE
    at errnoException (net.js:901:11)
    at net.js:1081:30
    at Object.5:1 (cluster.js:592:5)
    at handleResponse (cluster.js:171:41)
    at respond (cluster.js:192:5)
    at handleMessage (cluster.js:202:5)
    at process.EventEmitter.emit (events.js:117:20)
    at handleMessage (child_process.js:318:10)
    at child_process.js:392:7
    at process.handleConversion.net.Native.got (child_process.js:91:7)
    at process.<anonymous> (child_process.js:391:13)
    at process.EventEmitter.emit (events.js:117:20)
    at handleMessage (child_process.js:318:10)
    at Pipe.channel.onread (child_process.js:343:11)

I tried using mod_proxy to establish a proxy which worked but there were errors in the pages script so the ui was not functional using mod_proxy

Any help is nice, I might just have to deal with it being on port 3001 but I hope somehow there is a way to point it directly to the subdomain

Thanks,

**Comment by AmiT177** [comment]
@cryptoj you already have a service running under port 80.

**Comment by digicontributer** [comment]
In order to run a node webserver on port 80 you need to use sudo but I wouldn't recommend it.

I noted you've tried apache mod_proxy but I usually find nginx to be a better solution. https://www.digitalocean.com/community/tutorials/how-to-set-up-a-node-js-application-for-production-on-ubuntu-16-04

**Comment by RushOnline** [comment]
U've must use frontend web-server. I'm recommend nginx.

**Comment by whywefight** [comment]
You can also just run it the normal way, make sure nothing is bind to 80 and fwd requests from 80 to xxxx with iptables. Or just bin it to port 80. both works

**Comment by TheHolyRoger** [comment]
Nginx.
