### ISSUE TITLE
Coinbase funds calculated incorrectly for KMD asset chains

### ISSUE THREAD

**Issue by leto** [iquidus/explorer#132]
For this transaction:

http://www.btch.host/tx/99714e673b3b39c08a5e02a245dcfddaa5ca89e09a9ee036017989b313f34b75

the explorer says that the entire amount is coinbase (.0022), when in reality that includes fees and only 0.0001 is coinbase. KMD asset chains like BTCH seem to break the assumption that a transaction has coinbase input OR fees, but not both.

This does not seem to be specific to BTCH, others have confirmed it on other coins.

**Comment by TheComputerGenie** [comment]
Miner fees are included in the coinbase transaction.
In your example...
Block 7423 has 2 transactions:
99714e673b3b39c08a5e02a245dcfddaa5ca89e09a9ee036017989b313f34b75 (the coinabase)
8f3a92c2ea62d6486787e1f3ce9587a8267fa68e40ff6287d65b9e270e629002 (a private tx)

the private tx has 11 inputs totaling 0.00750000
the private tx has 10 outputs totaling 0.00540000
0.0075-0.0054= 0.0021
0.0021+0.0001=0.0022
Because, Bitcoin!

**Comment by leto** [comment]
@TheComputerGenie I think this comes down to the fact that only KMD asset chains mix together actually brand new coins, i.e. coinbase, and fees (existing money), in the "verification reward" (because it's not quite mining). To me, "coinbase" is only coins that have never existed, being added to the circulation. Fees are not coinbase, by definition, because they are being paid by an existing BTCH owner. Explorers never had to deal with this edge case.

I am happy to just close this issue and go about my coding 😈

**Comment by TheComputerGenie** [comment]
> To me, "coinbase" is only... 

Well, to you and to the protocol seem to be different things.
