### ISSUE TITLE
[FEATURE REQUEST] Graviex api v2

### ISSUE THREAD

**Issue by gregorst3** [iquidus/explorer#150]
Hello, is it possible to add the graviex api v2?
https://graviex.net/documents/api_v2?lang=en#!/markets

**Comment by poseidondev** [comment]
I second this request

**Comment by mrmetech** [comment]
no it isn't as easy as you might think this is because Graviex has most of there api under private which is a pain to do anything with

**Comment by poseidondev** [comment]
what about crex24 or bitebtc? :)

**Comment by Al3xxx19** [comment]
it has been done here https://github.com/Igor-san/sub1x-explorer

**Comment by uaktags** [comment]
https://github.com/DSTRACoin/diquidus/blob/master/lib/markets/graviex.js already did this in a more complete version than sub1x. It turns out it definitely is as easy as one things. Everything needed for testing can be found here:
https://github.com/uaktags/iquidus-explorer-exchanges/tree/master/graviex

**Comment by cannonballdex** [comment]
Implemented Graviex Market on Iquidus explorer. The page loads with no data, any ideas. I assume this is something simple, but spinning my wheels on it and there is not much information past here on the issue. Thanks for any reply.
