### ISSUE TITLE
Is blockchain reorganization considered when new blocks arrive ?

### ISSUE THREAD

**Issue by GiorgosK** [iquidus/explorer#175]
I have noticed using iquidus as bitbay explorer that balances are not reported correctly and then upon investigation there was a particular block that was really rejected by the network (upon reorganization I suppose) but iquidus has kept it and the accepted block (which was approved by the network) is not saved by iquidus.  As a result the rejected block is used in calculating balances and of course balances are wrong.

**Comment by Igor-san** [comment]
Would like to have something like DisconnectBlock.

**Comment by uaktags** [comment]
To me this sounds like a reindex would be needed, otherwise how would we automatically know when we're suppose to do this?

**Comment by TheHolyRoger** [comment]
I don't see a way to do this other than monitoring the coin's debug.log or periodically scanning the chain for orphaned blocks

**Comment by uaktags** [comment]
I suppose, before closing this, the thing to take into consideration is that we already have a minimum number of confirmations. The only two times that I see this being an issue is if the rejection happened after that number of confirmations has occurred (at which you need to update your settings) or the chain was rolled back to a certain point (at which you should definitely have a reindex as well as make sure your peers on your coin is updated so you're grabbing from the "new" chain.

Otherwise you're talking about scanning the blockchain on an interval (from 1 - blockheight) just to check for rejections somehow.
