### ISSUE TITLE
New Explorer for list

### ISSUE THREAD

**Issue by samadsajanlal** [iquidus/explorer#222]
https://gamecredits.network is using iquidus

**Comment by TheHolyRoger** [comment]
Can you link the source for the fork please?

**Comment by samadsajanlal** [comment]
https://github.com/samadsajanlal/explorer

**Comment by uaktags** [comment]
Thanks @samadsajanlal , looks like that domain is for sale?
I see that the explorer is live here https://explorer.gamecredits.network/ but for how long? No reason to add an explorer if it's going to be gone soon (already dealing with that as is which is why listing in the readme isn't optimal)
I'd also look into our recent updates if you're looking to keep the explorer up to date.

**Comment by uaktags** [comment]
"Buy gamecredits.org, gamecredits.network, and electrum-game.org for BTC or any other liquid coin available at Coinbase. "

Closing
