### ISSUE TITLE
api endpoint /ext/getaddress/ with amounts and timestamps

### ISSUE THREAD

**Issue by vincetori** [iquidus/explorer#249]
Inside element ``last_txs`` are just ``vout`` and ``addresses`` available. If I want to query amount and timestamp of transactions, theoretically I could scan wanted transactions from endpoint ``/ext/getlasttxs/``, but usually I don't find older transactions here. 

So I don't see a reliable method to query amounts and timestamp of transactions. 

Really helpful would be to add ``amount`` and ``timestamp`` in endpoint ``/ext/getaddress/``as well.

**Comment by uaktags** [comment]
As far as I know, to do this correctly, you'll need to reindex after patching the code. getaddress => db.get_address => db.find_address merely is just returning what's in the address collection, so last_tx only has those two values, not amount/timestamp. So to do this properly, we'd need the sync to add them to it, but realize that you'll start getting a lot of duplicate records being stored, making the db a bit larger.

**Comment by uaktags** [comment]
@vincetori  you can take a look at what i did in the above PR. That should be able to be tweaked to your needs.

**Comment by vincetori** [comment]
@uaktags I don't doubt your implementation at all!
As far I can see, for me as api user it is not possible to fetch transaction timestamp and value. I'm calling transactions only for one reason: **to get timestamp and value**!

To fetch them from endpoint ``/ext/getlasttxs/`` does not work, because I older transactions might not delivered there.

Do you understand my problem?

**Comment by uaktags** [comment]
No I definitely understand your problem. I apologize, I didn't really include how this could be used/the end result. Just kinda tied it into a commit of dealing with masternodes. I wanted to point your attention to https://github.com/iquidus/explorer/pull/257#issuecomment-451456505 rather than the whole PR.

Then you get something like this:
http://127.0.0.1:3003/ext/getaddresstransactions/VT7UqdkWNBdxugaEbATAz5LgfnDCgAEMTF?start=0&length=3
which provides you with 
```
{"data":[["16th Jan 2019 22:58:38","61435733b3cd47eb9570990965abebf19569290576eee84082e03393be1abb04","+ 174.99998960"],["16th Jan 2019 22:35:24","d3d070f4583a7a991b184bef66eeac9a1797dc15e26f2bd4db41817d06690dba","+ 174.99998960"],["16th Jan 2019 21:51:11","9d0224c0ff30c698a3e05781007aec3003dc64b6d8b1975cda04f4ea92519b59","+ 174.99998960"]]
}
```
The code is completely unfinished and probably should have just been put into a gist, but i intend to come back to it. The idea was, hash = address you're trying to pull, start = the oldest block to reference, and then length = how many results you want. 

In practice with the way the code currently sits, it grabs everything in the database, returns from start being index of the results. So start = 0 is the most recent transaction for that address, 1 is the transaction just before the most recent, and so on. It should be a good starting point to clean up and get going to your full needs, if I don't get to it first.

It's 1 function in database.js and 1 function in app.js.

**Comment by TheHolyRoger** [comment]
Given the new functionality of getlasttxs in this PR https://github.com/iquidus/explorer/commit/8d44d4a8045f507a3fc5a2d42d1c40e34fa4d0dc

I think this issue can be closed?

I don't think the overhead this adds is beneficial...

**Comment by uaktags** [comment]
I'm in agreement. Closing.
