### ISSUE TITLE
Will Bitcoin Blockchain ever finish syncing? Quad Xeon doing <1 block/min

### ISSUE THREAD

**Issue by th3geek** [iquidus/explorer#265]
Hi everyone,

First, thanks to everyone who works on this great project!  

I'm concerned my sync.js worker may never finished syncing the Blockchain.  It's been syncing for over 10 days and I just hit block 131,000 today.  I'm very concerned because the sync is still in 2011 and the transaction volumes are very small compared to what will be FULL blocks and a flurry of activity.  Over the last 24 hours, it only processed ~1500 blocks (<1 per minute!)

I see people are working to fix this issue but ran into problems (bottom of  #257) 

How about building a docker swarm?  The instances can share a common data directory on the host where they share info (in text files) with the other workers (ex. which worker looks up which txids or how they'll divvy up remaining blocks, etc...)

Thoughts?

**Comment by th3geek** [comment]
So since I posted the previous post I've only moved from block 131,000 to 133650, so less than 3,000 blocks in 6 days of running straight.  Obviously this isn't going to finish before next year, if ever. I'm going to guess that people are only using this explorer for alternative blockchains since I don't think it would ever sync with bitcoin.

Guess I'll look for another project since this one doesn't seem to be active.

**Comment by uaktags** [comment]
Yea, this has been brought up a number of times already, and it really comes down to how many txes are in a block, how long the jsonRPC takes to render, and then how long parsing all of that and getting into mongo takes. A few Issues have brought up ideas on how to speed up, but thus far there hasn't been any PRs to mitigate against it. One avenue, specifically for BTC, that I was looking into was modifying BitcoinDatabaseGenerator (it's on github) to use mongo instead of MSSQL, and change the schema to match iquidus. That uses the actual block files rather than the RPC which should make the process much faster, but have't gotten anywhere with that yet.

**Comment by uaktags** [comment]
I may have a solution to get faster that I'm testing out by cutting out the bitcoin-node-api and using bitcoin-core directly. Preliminary results on up to 10k of another coin was 25% faster. I'm currently syncing bitcoin to test my update with that using just a AMD Ryzen 1700x. Shall see how that fairs.

**Comment by uaktags** [comment]
@th3geek not sure if you're still actively pursuing this, but I've posted about clustering in my PR. While I don't have a Quad Xeon to test with, on a 1700x I've made to to block 170k in about 2hours. Granted this was with 8cores/16threads, so 16 clustered processes.

**Comment by TheHolyRoger** [comment]
Massive improvements in https://github.com/iquidus/explorer/commit/8d44d4a8045f507a3fc5a2d42d1c40e34fa4d0dc but more to come too.
