### ISSUE TITLE
Explorer transactions list not in order and behaving unexpectedly. 

### ISSUE THREAD

**Issue by BarneyChambers** [iquidus/explorer#291]
We are running an Iquidus explorer for the Buenos blockchain at explorer.buenos.io . It's currently showing transactions in a weird order, and despite deleting the blockchain, reindexing the explorer and trying everything else I can think of, the explorer continues to show random transactions.

It is showing the correct number of blocks in the bottom right, but the `latest transactions` list is completely out of order

<img width="1272" alt="unexpected" src="https://user-images.githubusercontent.com/8683916/61795174-24def700-ae66-11e9-92d7-55440b7ba2fa.png">

Buenos is a bitcoin fork and doesn't have any super crazy new features that would break the explorer.

**Comment by uaktags** [comment]
Currently I see quite the opposite of what's being displayed in the image. I see you're in the 17k range of blocks, their in order, and looks to be syncing.

My guess is you or someone manually looked at some random blocks, which caused Iquidus to index the un-indexed blocks, before the sync script caught up.

**Comment by BarneyChambers** [comment]
> Currently I see quite the opposite of what's being displayed in the image. I see you're in the 17k range of blocks, their in order, and looks to be syncing.
> 
> My guess is you or someone manually looked at some random blocks, which caused Iquidus to index the un-indexed blocks, before the sync script caught up.

Thanks for your comment. This explorer has been left untouched just like explorer.braz.io and explorer.veggiecoin.io, and no one has access to the daemon or explorer backend to do any lookups or anything like that. I think this might actually be a bug

**Comment by uaktags** [comment]
I should have been more clear, it's not the backend or daemon that I mean in terms of these queries, but API and physical searches. For instance, you can query a block before it is syncd by using the search feature and it will typically hit and show up on the latest transactions in what appears to be out of order.

However, like I said, I can't see this bug because it's currently in order (and up to date with the daemons block count). I can look to see if the current master branch has the sort forced like most of the forks do, but outside of that, there's no way for the sync tool to skip around. It starts from last block # indexed(0 on a reindex) and goes all the way up until getblockcount. It's single threaded and goes in order.

**Comment by TheHolyRoger** [comment]
Fixed in https://github.com/iquidus/explorer/pull/319 awaiting more feedback before merging

**Comment by TheHolyRoger** [comment]
Merged in https://github.com/iquidus/explorer/commit/8d44d4a8045f507a3fc5a2d42d1c40e34fa4d0dc
