### ISSUE TITLE
Server DIES while indexing/reindexing

### ISSUE THREAD

**Issue by EndCiv** [iquidus/explorer#32]
Everything seems to be working smoothly... AND THEN
My server goes dead - falls offline.. 
all my ssh windows timeout and my remote server shows OFFLINE.
All my clients and wallets ping out. .. 
and I have to login to my remote console and restart it.

I figured it was because the flow of information being displayed to me across the bitwaves was too great and tried to reindex w/node scripts/sync.js index reindex - in a backgrounded screen, but it also seems to exhibit the same issues.

Gonna have to restart everything again.

**Comment by EndCiv** [comment]
Things seem to be *better* after running:
node scripts/sync.js index check
with: node --stack-size=10000 bin/instance

But it's *VERY* slow going and does eventually crap out the 
'node scripts/sync.js index check'  process.. so I have to rm /tmp/index.pid
and restart 'node scripts/sync.js index check'
When the process dies, this is the output:

> /explorer/lib/explorer.js:338
>           module.exports.syncLoop(tx.vout.length, function (loop) {
>                                          ^
> TypeError: Cannot read property 'length' of undefined
>    ~/explorer/lib/explorer.js:338:42
>     at Request._callback (~/explorer/lib/explorer.js:113:14)
>     at Request.self.callback (~/explorer/node_modules/request/request.js:121:22)
>     at Request.emit (events.js:110:17)
>     at Request.<anonymous> (~/explorer/node_modules/request/request.js:985:14)
>     at Request.emit (events.js:129:20)
>     at IncomingMessage.<anonymous> (~/explorer/node_modules/request/request.js:936:12)
>     at IncomingMessage.emit (events.js:129:20)
>     at _stream_readable.js:902:16
>     at process._tickCallback (node.js:343:11)

**Comment by iquidus** [comment]
Try launching using forever. To install globally 
sudo npm install -g forever
Then to launch a single instance of the explorer, from inside explorer root dir
forever start bin/instance

What coin are you trying to run this with? When extremely slow this is due to the rpc server responses taking a lot of time. the explorer should not be locking up your VPS, however the wallet daemon often can. 

Use the --stack-size flag on the sync script, e.g
node --stack-size=15000 scripts/sync.js index reindex

Let me know how you get on.

**Comment by EndCiv** [comment]
> What coin are you trying to run this with? 
"BOB" Dobbscoin - The Currency of the Econocolypse. 
http://www.dobbscoin.info

No luck with node forever .. the slow issue is only when using 
scripts/sync.js index check - and anything other than check causes data to run by so fast, resulting in the serer falling over, which is strange, because I can watch data fly past even faster w/ 'tail -f ./dobbscoin debug.log' while reindexing a block chain in the wallet and the box never dies.

check does eventually fail.. and I have to rm tmp/index.pid and restart the check.. Maybe I can just limp along with 'check' - restarting it every 4k blocks.. but we're on block 158440, so that'd take a while. Maybe I can sick forever on 'scripts/sync.js index check' -hmmm, will try.  komput0r isn't really my strong suit.

**Comment by iquidus** [comment]
check always starts from the beginning, its purpose is to check for any missed txs.

have a play with these settings: https://github.com/iquidus/explorer/blob/master/settings.json.template#L43

check is defaulted to 250ms, which is why its slower than an update/reindex (default 10ms).
they determine the how long to pause between requests.

I'm not familar with dobbscoin, but very familiar with bob and the church ;) will take a look when i get a chance.

**Comment by EndCiv** [comment]
I've changed settings.json to

>   //update script settings
>   "update_timeout": 250,
>   "check_timeout": 250,

and it's chugging along. memory is low/cpu is low.
I'll keep at it, the LUCK PLANE will provide.

**Comment by EndCiv** [comment]
**Could it be my settings.json?**
_Perhaps you could verify my hash data using our existing explorer.
http://explorer.dobbscoin.info_

>   // ensure links on API page are valid
>   "api": {
>     "blockindex": 158100,
>     "blockhash": "291654ed9dfc6254bd0cc470b013fb2a0fddcf1bc62f58e5b4d714cad0cd44e1",
>     "txhash": "9f751d844378b61ae2eeb4864d65cf568e34ab07a80081cc2b62d1bfb3d93cc4",
>     "address": "1DxvtzyCriEzTakdiFuvVs2TCTxh5ypUyk"
>   },
> 

And for genesis block, that's block zero, right?

>   //genesis
>   "genesis_tx": "21e66ff8b6f14eb3fa0edf35dc93440a751fdddb421965c88029ad0048d98ca1",
>   "genesis_block": "6d2d7d525900712451b9697d0b5b2304ebae6efb349540da445bf575c0159969",
>

**Comment by EndCiv** [comment]
An Australian user/member/cultist was able to pull it off.
http://iquidus.slackprojects.org
Will eventually be hosted at http://explorer.dobbscoin.info

Thanks for the helps.
