### ISSUE TITLE
V 1.7.3 Duplicate key "time" error

### ISSUE THREAD

**Issue by BayerTM** [iquidus/explorer#337]
Hi Roger,

I have installed explorer V1.7.3 and have a Duplicate key "time" error
i have updated everything to the newest versions Mongo 4.2.2 Node 13.5.0 
i have allso set the settings.json file
I have also dropped the hole mongo database and the user and made a new one nothing helped.
Do you have any clue for this problem i dont thing there is problem with the explorer i am doning something wrong.
When i use the reindex commando i get this error see image file.
Thank you for your time!

![ice_screenshot_20200105-162405](https://user-images.githubusercontent.com/59299109/71782869-44667800-2fdf-11ea-9181-96d6b24d7d1e.png)

**Comment by BayerTM** [comment]
I see i have nodejs version v 8.10.0 and node version 13.5.0
i tought node and nodejs where the same do i need update nodejs?

**Comment by TheHolyRoger** [comment]
Hi @BayerTM , it sounds like you're using the same dodgy codebase as seen in this issue: https://github.com/iquidus/explorer/issues/335

The problem lies in your coin's core client - your RPC spits out malformed JSON with duplicate keys.

See this link for the example problem lines in digitalcoin: https://github.com/iquidus/explorer/issues/335#issuecomment-570130051
