### ISSUE TITLE
TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by admecoin** [iquidus/explorer#346]
Error
I can’t synchronize to the end of the explorer. Error:

TypeError: Cannot read property '0' of undefined
    at /root/explorer/lib/explorer.js:290:74
    at Object.next (/root/explorer/lib/explorer.js:189:18)
    at Object.syncLoop (/root/explorer/lib/explorer.js:205:10)
    at Object.prepare_vout (/root/explorer/lib/explorer.js:284:20)
    at /root/explorer/lib/database.js:141:17
    at /root/explorer/lib/explorer.js:396:14
    at Object.next (/root/explorer/lib/explorer.js:194:24)
    at /root/explorer/lib/explorer.js:382:22
    at Object.convert_to_satoshi (/root/explorer/lib/explorer.js:25:12)
    at /root/explorer/lib/explorer.js:380:30
    at /root/explorer/lib/explorer.js:263:14
    at Object.next (/root/explorer/lib/explorer.js:194:24)
    at Object.syncLoop (/root/explorer/lib/explorer.js:205:10)
    at Object.is_unique (/root/explorer/lib/explorer.js:252:20)
    at /root/explorer/lib/explorer.js:378:26
    at /root/explorer/lib/explorer.js:362:20

**Comment by minkcrypto** [comment]
Try loading block 1 at your explorer page please

**Comment by admecoin** [comment]
246873 blocks are already synchronized, further synchronization is interrupted. Total blocks over 400,000

**Comment by uaktags** [comment]
I'm guessing you're on 1.6.x of iquidus,
I can't begin to guess what coin you're using,
etc

please include more details about the error and the environment. Are you able to sync at all (you could reindex, but gets stuck at a certain height), can you not sync at all, etc?

Eitherway, the issue is within the prepare_vout function
```
        module.exports.is_unique(arr_vout, vout[i].scriptPubKey.addresses[0], function(unique, index) {
```

So the error is saying that there's no addresses in vout[i].scriptPubKey when there should be. So it failed here. The explorer can't/doesn't know how to react to this missing data. Check what that transaction would be and see what's the json looking like for the scriptPubKey addresses.

**Comment by TheHolyRoger** [comment]
Dup of https://github.com/iquidus/explorer/issues/56
