### ISSUE TITLE
front page shows each tx hash separately.  is this a setting? 

### ISSUE THREAD

**Issue by michelvankessel** [iquidus/explorer#359]
Hi,

For some reason each tx hash is shown separately on the front page. I don't recall this was like this in the past. Is this a setting? I cannot seem to find it. 

![image](https://user-images.githubusercontent.com/16052447/76159226-70f15a00-611e-11ea-87f1-0a1b9ab6791c.png)

**Comment by uaktags** [comment]
Always been like this. "Latest Transactions" is the name of the page. This is not a setting, as we don't store blocks, only transactions

**Comment by michelvankessel** [comment]
I got confused, because we are running an older version, showing only one of the hashes

![image](https://user-images.githubusercontent.com/16052447/76248574-e4d85300-6241-11ea-95a3-b38a44ed8aa5.png)

**Comment by michelvankessel** [comment]
@uaktags do you know why the older vs newer version shows the 0 recipients hash?

**Comment by uaktags** [comment]
What does the json of the blockchain show for those transactions? I know, due to other coins that have 0 vout txes, we've recently allowed these to go in so that the sync doesn't break. So my guess is that if you were to check these manually via the JSON, you'll find that your coin is showing these transactions as having vins (inputs) but no vouts (outputs).

**Comment by uaktags** [comment]
Here's an example from your coins official explorer at cryptoid:
https://chainz.cryptoid.info/blk/tx.dws?7794884.htm
Your coin has non-standard transactions. We now account for those too. No vouts.

**Comment by michelvankessel** [comment]
thank you for explaining this ! @uaktags
