### ISSUE TITLE
BLOCK ZERO

### ISSUE THREAD

**Issue by dobbscoin** [iquidus/explorer#38]
It hasn't happened in the last 100 Blocks, but..
We were getting quite a few BLOCK ZERO blocks, 
with a timestamp of: 1st Jan 1970 00:00:00

Such as this one:
http://explorer.dobbscoin.info/tx/f991920a70616a2c09fe03c588784050625ffface03e9989f89497f996991af3

I started a thread on our forum to investigate and document the issue when I thought it might be related to how our faucet interacts with the iquidus explorer. I'll keep an eye on it and keep updating any future BLOCK ZERO info there.

Is there a iquidus 2.0 in the works?

http://dobbscoin.info/smf/index.php?topic=178.msg656;topicseen#new

**Comment by iquidus** [comment]
ah, I am aware of this issue. essentially it's due to someone loading the tx via the explorer, forcing it to index it, before it has been accepted into a block (note the non existent blockhash). It's on my todo list to fix. Just trying to determine the best approach, as everything has pros and cons. 

i first encountered this with a tipbot, as when it sent the tip it would also give url to tx in explorer, if a user clicked it before it was in a block, this same issue would occur. 

yes, iquidus 2.0 is in the works.

**Comment by iquidus** [comment]
Also, you can fix these by re indexing. however that wont prevent it from occurring again until the fix/update.

My apologies for this, it is something that slipped through testing for a very long time, and was not reported until quite recently.

**Comment by dobbscoin** [comment]
No broblama. Best block exploder out there fer the money, keep up the good work.
