### ISSUE TITLE
Duplicate key "time"

### ISSUE THREAD

**Issue by grigzy28** [iquidus/explorer#434]
Error Duplicate key "time" ????  Not sure what that means exactly, but any help would be appreciated.
Explorer ver 1.7.4, nodejs 12.20

```
root@shawnvps031:~/404explorer# nodejs scripts/sync.js index reindex
script launched with pid: 7248
TXs cleared.
Addresses cleared.
Address TXs cleared.
index cleared (reindex)
Error:  {
  name: 'SyntaxError',
  message: 'Duplicate key "time"',
  at: 716,
  text: '[{"result":{"hex":"010000003966bc5e010000000000000000000000000000000000000000000000000000000000000000ffffffff03510118ffffffff0100e87648170000001976a914d5933eb53747885612f47de9750672e8a4bd6a6688ac00000000","txid":"92ebe15d70cc07c4b32f8d8b9729dc8045abc2688cc76451744bafa70573b57c","version":1,"time":1589405241,"locktime":0,"vin":[{"coinbase":"510118","sequence":4294967295}],"vout":[{"value":1000.00000000,"n":0,"scriptPubKey":{"asm":"OP_DUP OP_HASH160 d5933eb53747885612f47de9750672e8a4bd6a66 OP_EQUALVERIFY OP_CHECKSIG","reqSigs":1,"type":"pubkeyhash","addresses":["4ZB7CVG6P4wagGjfq6zWVKNWwEcmmZ29br"]}}],"blockhash":"0000028e8b33a043ed98b66cc9fec2a8c23d9c0357cd59c4f4c14188d7cd6d2a","confirmations":95773,"time":1589405465,"blocktime":1589405465},"error":null,"id":"1610721385592-0"}]\n'
}
Error:  {
  name: 'SyntaxError',
  message: 'Duplicate key "time"',
  at: 716,
  text: '[{"result":{"hex":"010000001e67bc5e010000000000000000000000000000000000000000000000000000000000000000ffffffff03520105ffffffff0100e87648170000001976a914d5933eb53747885612f47de9750672e8a4bd6a6688ac00000000","txid":"6d045d8ddfe084b4071098a7b934aaf749ac26243344ee56a437fa44cf5f2ea4","version":1,"time":1589405470,"locktime":0,"vin":[{"coinbase":"520105","sequence":4294967295}],"vout":[{"value":1000.00000000,"n":0,"scriptPubKey":{"asm":"OP_DUP OP_HASH160 d5933eb53747885612f47de9750672e8a4bd6a66 OP_EQUALVERIFY OP_CHECKSIG","reqSigs":1,"type":"pubkeyhash","addresses":["4ZB7CVG6P4wagGjfq6zWVKNWwEcmmZ29br"]}}],"blockhash":"0000010cfc64696699bc5f077c2d70f6679f570ded213ef4a36a2d737e8460d0","confirmations":95772,"time":1589405498,"blocktime":1589405498},"error":null,"id":"1610721385594-0"}]\n'
}
Error:  {
  name: 'SyntaxError',
  message: 'Duplicate key "time"',
  at: 716,
  text: '[{"result":{"hex":"010000004267bc5e010000000000000000000000000000000000000000000000000000000000000000ffffffff03530109ffffffff0100e87648170000001976a914d5933eb53747885612f47de9750672e8a4bd6a6688ac00000000","txid":"c37c2b9a521ed92cb07eef03dc549eb44b7392733b76fb397cbc932eccc41f38","version":1,"time":1589405506,"locktime":0,"vin":[{"coinbase":"530109","sequence":4294967295}],"vout":[{"value":1000.00000000,"n":0,"scriptPubKey":{"asm":"OP_DUP OP_HASH160 d5933eb53747885612f47de9750672e8a4bd6a66 OP_EQUALVERIFY OP_CHECKSIG","reqSigs":1,"type":"pubkeyhash","addresses":["4ZB7CVG6P4wagGjfq6zWVKNWwEcmmZ29br"]}}],"blockhash":"000002e58bfdbb07faf43ad7c787d1a1cc1e9cf50a8c1ebd5b367eae86e4b5ca","confirmations":95771,"time":1589405562,"blocktime":1589405562},"error":null,"id":"1610721385595-0"}]\n'
}
```

**Comment by joeuhren** [comment]
The error msg couldn't be any more clear. You literally have two "time" entries with different values in the block that is failing to be read. Look here for more info and a possible fix for the blockchain code itself: [https://github.com/iquidus/explorer/issues/335](https://github.com/iquidus/explorer/issues/335)

While this is definitely a case of POOR BLOCKCHAIN CODING, it is my understanding that the json standard is actually a bit gray and doesn't specifically state that duplicate keys are prohibited: [https://dzone.com/articles/duplicate-keys-in-json-objects](https://dzone.com/articles/duplicate-keys-in-json-objects). So imo, iquidus should probably handle this by taking the 1st unique value and ignoring any duplicate values without crashing.

I did a tiny bit of digging and I think this is from trying to sync 404 coin, right? Regardless, can you link to the wallet source code and/or provide a link to a working linux wallet so that I can test this and see about providing a fix from this end?

**Comment by grigzy28** [comment]
Yes, this is the 404 coin.  The person who coded the coin has erased the repo from his github, however I do have a copy of the source code from which I had built the linux daemon from.  In the clients folder in the file is an already compiled linux daemon/qt and windows wallets.
 
[404coin_2020new-master.zip](https://github.com/iquidus/explorer/files/5825334/404coin_2020new-master.zip)

**Comment by grigzy28** [comment]
Also, if you do then you'll need some nodes to download the chain from.
addnode=47.34.121.15
addnode=216.21.165.61
addnode=94.55.180.53
addnode=100.2.198.95
addnode=186.88.13.239

**Comment by Javed-PK** [comment]
Remove line from src/rpcrawtransaction.cpp : 

entry.push_back(Pair("time", (int64_t)pindex->nTime));

and recompile it.

**Comment by grigzy28** [comment]
That works, thank you.

**Comment by joeuhren** [comment]
I'm glad there was a better solution, but just for reference from the iquidus side, I was able to track the issue back to the bitcoin-core module (v2.0.0) which makes it tricky to solve since the problem code isn't even directly available to the explorer. I had tried updating to v3.0.0 but that breaks syncing and I don't have time to debug that yet to see if it would solve the duplicate key issue. As previously mentioned, it was a case of bad blockchain programming to begin with so I'm glad it was resolved at the source.

**Comment by grigzy28** [comment]
Yes, I'm glad it works too.  So far no other issues have come up with syncing, working just like all y other explorers.  We can close this or leave it open to possibly look into later on when there is time or if you would like the explorer to be able to handle such occurrences.

**Comment by uaktags** [comment]
Closing as issue resolved. This is a typical issue we run into with these altcoins, unfortunately alot of the source coins that get copied from really do a spaghetti code job. I do want to say, good work everyone on getting to the bottom of that quickly.
