### ISSUE TITLE
Will this work with bitcoin?

### ISSUE THREAD

**Issue by Demessfor** [iquidus/explorer#452]
Will this work with bitcoind 0.21?
Which version of Node.js, Mongo and Ubuntu do you recommend for the current time?

**Comment by joeuhren** [comment]
Bitcoin support hasn't been officially merged yet, but you can manually apply the changes to your own explorer instance from https://github.com/iquidus/explorer/pull/440

Newest versions of node.js, mongo and ubuntu are always recommended if you are creating a new instance.

That being said, I cannot stress enough that syncing bitcoin from scratch will take an insane amount of time. Syncing the actual bitcoin daemon only takes 1-2 days with a fast connection, but syncing all transactions with iquidus will take months, and that's assuming you have a fast computer to do it on (NVMe drive is a must, plus tons of RAM and at least 10+ cores i9 cpu recommended). With those specs running 20 concurrent threads, I was syncing an average of 400 blocks per hour (the first 100k blocks sync fairly quickly but slow to a crawl once blocks start getting bigger), which would take about 60 days while running the sync 24/7. If you don't have a fast machine to do this on, it will literally take years because of the sheer amount of data to parse through. You have been warned.

**Comment by uaktags** [comment]
I'm closing only for the simple reason that while YES it is possible and can be support, the above notice from @joeuhren really make it pretty unlikely of a use case.
