### ISSUE TITLE
Help/Feature Request->docker-compose

### ISSUE THREAD

**Issue by waterfallm** [iquidus/explorer#453]
Does anyone have a working docker-compose file to get this project up and running quickly?

**Comment by joeuhren** [comment]
Nope, but good luck!

I could be wrong but I think you may have a difficult time finding or creating some kind of generic docker setup for the explorer. There are a number of configurable options that need to be set before the explorer will work correctly (many can be left at their defaults but at least a few need to be specifically configured to your particular coin wallet and mongo database settings with unique logins and passwords).

Unless you configure the docker image to allow passing hundreds of settings then whatever docker image you find would only work for a specific coin and most likely wouldn't be the same coin you need it for.

That being said, I find it's actually quite easy to setup the explorer from scratch (Keep in mind I've literally done it 100's of times over the years).

Install pre-requisites:
- Node.js
- MongoDb
- Your coin daemon

Then follow the 7-8 steps from the top of https://github.com/iquidus/explorer and you're ready to sync.

Which part of the setup are you having troubles with that you think docker will solve for you?

**Comment by uaktags** [comment]
I've been using the following one in my server only because I'm too lazy to actually fix it up myself:

https://hub.docker.com/r/maza/mazanode-iquidus/dockerfile/
https://github.com/mazanetwork/mazanode/tree/master/iquidus

After that I just modified the container as and replaced their Dockerfile with updates i needed to go back to the main iquidus repo.

**Please note, we are not affiliated with mazanode and i'm only posting them as a public example to answer your question.**
