### ISSUE TITLE
settings.json not updating

### ISSUE THREAD

**Issue by cibadmin** [iquidus/explorer#455]
hi,

I wanted to update some data like enabling api and market, when I installed iquidus i was disabling them (false) now need to enable (true) and add my twitter etc but when i did that i didn't see the explorer updated
logged in ssh as root then:
cd $HOME/explorer
npm stop
nano settings.json -t
screen
npm start  
is it right or something is wrong?

any help?

PS: I am using v1.6.1

Thx

**Comment by joeuhren** [comment]
Are you 100% sure that you are stopping the explorer properly? When you run `npm stop` for example, do you get any error msg and/or can you still access the explorer website after that? I'm not exactly sure why, but it seems that maybe you aren't actually shutting down the explorer and that is why it isn't picking up the new config changes.

You have the right idea though. All you need to do is stop the explorer, make changes to the config and start up the explorer again for it to immediately pick up the new config changes.

If all else fails, try a reboot, but of course that's a bit overkill to do after each config change.

**Comment by cibadmin** [comment]
> Are you 100% sure that you are stopping the explorer properly? When you run `npm stop` for example, do you get any error msg and/or can you still access the explorer website after that? I'm not exactly sure why, but it seems that maybe you aren't actually shutting down the explorer and that is why it isn't picking up the new config changes.
> 
> You have the right idea though. All you need to do is stop the explorer, make changes to the config and start up the explorer again for it to immediately pick up the new config changes.
> 
> If all else fails, try a reboot, but of course that's a bit overkill to do after each config change.

yes you are right I am getting this error:

root@server:~# cd $HOME/explorer
root@server:~/explorer# npm stop

> explorer@1.6.1 stop /root/explorer
> kill -2 $(cat tmp/cluster.pid)

sh: 1: kill: No such process

npm ERR! Linux 4.4.0
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "stop"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! explorer@1.6.1 stop: `kill -2 $(cat tmp/cluster.pid)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the explorer@1.6.1 stop script 'kill -2 $(cat tmp/cluster.pid                                                                             )'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the explorer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     kill -2 $(cat tmp/cluster.pid)
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs explorer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls explorer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/explorer/npm-debug.log
root@server:~/explorer#

**Comment by cibadmin** [comment]
after some search i fixed the above error and npm start correctly as you will see below but i am not getting the error that i am getting upon npm start any help?

root@server:~# cd $HOME/explorer
root@server:~/explorer# npm stop

> explorer@1.6.1 stop /root/explorer
> kill -2 $(cat tmp/cluster.pid)

root@server:~/explorer# nano settings.json -t
root@server:~/explorer# npm start

> explorer@1.6.1 start /root/explorer
> node --stack-size=10000 ./bin/cluster

Starting cluster with pid: 24668
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: bind EADDRINUSE null:3001
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at listenOnMasterHandle (net.js:1427:16)
    at rr (internal/cluster/child.js:121:12)
    at Worker.send (internal/cluster/child.js:88:7)
    at process.onInternalMessage (internal/cluster/utils.js:42:8)
    at emitTwo (events.js:131:20)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Cluster restarting...
events.js:183
      throw er; // Unhandled 'error' event
      ^

**Comment by joeuhren** [comment]
I'm not quite sure if the problem you are having is due to using an outdated version of the explorer or if perhaps the `screen` command is causing some kind of grief. The `Error: bind EADDRINUSE null:3001` msg is telling you that port 3001 is already in use which is most likely because the explorer did not properly shut down earlier for whatever reason.

I typically use [forever](https://www.npmjs.com/package/forever) to startup production sites and `npm start` when setting up and debugging new sites, but I always stop the explorer with CTRL+C instead of opening another window and using `npm stop`, although that won't work if you use `screen`.

**Comment by uaktags** [comment]
the EADDRINUSE is saying that it's definitely still running (never stopped). It didn't stop because it failed at `kill -2 $(cat tmp/cluster.pid)`

With a reproducible issue, from the root of the explorer directory, do a ``cat tmp/cluster.pid`` and see what comes out.
```
/app $ cat tmp/cluster.pid
34
/app $
```
 Then you can run ``ps aux | grep <cluser's proccess ID>`` and see if its still running, or do a ``ps aux | grep bin/cluster``.
 ```
 /app $ ps aux | grep 34
   34 iquidus    0:00 node --stack-size=10000 ./bin/cluster
  134 iquidus    0:31 /usr/local/bin/node --stack-size=10000 /app/bin/cluster
23610 iquidus    0:00 grep 34
```
```
/app $ ps aux | grep bin/cluster
   33 iquidus    0:00 sh -c node --stack-size=10000 ./bin/cluster   <== this is just from my docker's entrypoint
   34 iquidus    0:00 node --stack-size=10000 ./bin/cluster            <== this is the actual cluster command
```
  You can also get the process id from ``netstat -plant | grep node`` to see its infact running and still taking that port
  ```
  /app $ netstat -plant | grep node
tcp        0      0 :::3001                 :::*                    LISTEN      34/node
```

If that all matches, something's wrong with your node environment running the stop command which doesn't seem like an iquidus issue.

you can further verify by running ``echo $(cat tmp/cluster.pid)``. This is really just simple bash/sh command logic ``$(cat tmp/cluster.pid)`` is catting the .pid for the process id and contains it into a blank variable (or whatever the actual terminology is), and it gets passed to kill -2 (again another linux command and not nodejs/iquidus specific) or in the case of the example, passes it to echo.
```
/app $ echo $(cat tmp/cluster.pid)
34
```

So with that. I'm going to close the comment, please feel free to reopen if you feel this is incorrect and we have something further to look into. Hope all that helps though.
