### ISSUE TITLE
Display OP_RETURN data

### ISSUE THREAD

**Issue by johnrigler** [iquidus/explorer#465]
I inject data into the ledger in various ways. Most notably, I hack text directly into fake addresses with https://github.com/johnrigler/unspendable. Of course the gold-standard of data on the ledger is the OP_RETURN field. The easiest way to interpret this data is as ASCII text. Here is an example that points to this very project:

https://digibyteblockexplorer.com/tx/ac8e49a6a11f6e513bc4a5f82e277e9a9cf40d4cbddf22233a292ba289ec2bdd

In the "data" field, I added a URL. In iquidus, this field doesn't appear. So before I start hacking away at "views/tx.pug" in order to get the URL to appear at the bottom, I am curious of anyone else is interested in this project and has already come up with a solution. 

Current project: http://ledger.church:3001

Thanks

**Comment by johnrigler** [comment]
![Screen Shot 2021-05-29 at 9 37 40 AM](https://user-images.githubusercontent.com/7305117/120074263-a656d000-c061-11eb-8b9f-fbd628179b69.png)

Here is an example of what the transaction might look like with this data displayed.

**Comment by uaktags** [comment]
Hey @johnrigler 
My apologies in, proactively, being wrong as I've been away from this project for FAR too long and only now starting to chime in before getting back (hopefully soon) to full time development again.

So my initial theory is that we need a few changes:

``lib/explorer.js``
https://github.com/iquidus/explorer/blob/5f33fea620701db019f4bd4dae28bc0e28a53a67/lib/explorer.js#L500
```
if (vout[i].scriptPubKey.type != 'nonstandard' && vout[i].scriptPubKey.type != 'nulldata') { 
...
...
} else {
// no address, move to next vout
loop.next();
}
```
So in here, because the OP_RETURN in your example has a type of "nulldata" we actually don't process or save this anywhere:
```
"asm": "OP_RETURN 68747470733a2f2f6769746875622e636f6d2f697175696475732f6578706c6f726572",
        "hex": "6a2368747470733a2f2f6769746875622e636f6d2f697175696475732f6578706c6f726572",
        "type": "nulldata"
```

so that's the first thing that'll need to get handled, adding that transaction to mongo by working with the else to add something like:
```
} else if(vout[i].scriptPubKey.type == 'nulldata' && vout[i].scriptPubKey.asm.startsWith("OP_RETURN")) {
// Handle this transaction.
// Bascially need a way to just decode Hex to ASCII
} else {
// no address, move to next vout
loop.next();
}
```

Now that's just a wild guess, as I'm still trying to remember how our tx page handles the information (pretty sure its solely grabbing from mongo, but don't quote me on that). I also suspect that within ``https://github.com/iquidus/explorer/blob/5f33fea620701db019f4bd4dae28bc0e28a53a67/routes/index.js#L49-L100`` that a change will need to be handled as well (or in lieu of the above).

I personally don't have any coins that I can test this on, knowing the output will be there to determine if I got it, but hopefully this idea helps out a bit.

**Comment by uaktags** [comment]
Closing, no further response, no coins available to test with, very coin-specific.
