### ISSUE TITLE
Cronjob not working

### ISSUE THREAD

**Issue by suzandi** [iquidus/explorer#468]
Hello,

After installing the script, updating the database, the blockchain is synced, but the cronjobs won't run or run but not working, there is no error in debug or cronjob error log, I can only update the index if I manually type:

node scripts/sync.js index update.

Is there any resolvation?

**Comment by joeuhren** [comment]
In most cases, you must specify the full path to both the explorer and node.js in a cron job. A cmd like `node scripts/sync.js index update` will not work in crontab because of the incomplete paths. If you don't know where your node.js is installed, you can run the cmd `which node` to find the node path.

Example paths:
Explorer: `/home/username/explorer`
node: `/home/username/.nvm/versions/node/v14.16.1/bin/node`

Given the sample paths above, the index update cmd would look like this:

```
*/1 * * * * cd /home/username/explorer && /home/username/.nvm/versions/node/v14.16.1/bin/node scripts/sync.js index update > /dev/null 2>&1
```

Hopefully that helps point you in the right direction.

**Comment by uaktags** [comment]
I agree with Joe.

Perhaps provide what your cronjob is. In the readme we also provide that you should use the path to node ``/usr/bin/node``.

**Comment by suzandi** [comment]
Stupid me. Somehow when the first time I installed it, it works with this crontab example:

*/1 * * * * cd explorer && /usr/bin/nodejs scripts/sync.js index update > /dev/null 2>&1

But my node now was on another location. Doing which node to find the location and changing on the crontab completely solve the issue!

Many thanks guys!

**Comment by pacman809** [comment]
Close the issue?

**Comment by suzandi** [comment]
Yes please, many thanks!
