### ISSUE TITLE
While refreshing the explorer randomly got this error

### ISSUE THREAD

**Issue by rameshjois** [iquidus/explorer#476]
<img width="891" alt="image001" src="https://user-images.githubusercontent.com/86937049/129997569-186d96bb-e32c-42b9-9116-06b56092c84f.png">

Randomly refreshed the explorer, this error popped up, this came multiple times before too but randomly

**Comment by uaktags** [comment]
Did you see anything inside of the console output?

If you didn't capture an error, could you try reproducing it and seeing what it gives you in the terminal that's running ``npm start``

Basically, my assumption is you're getting this due to some hiccup or timeout coming from the node/express instance as it handles the REST API used for datatables.

The error itself is saying that we told the table to initialize but the data wasn't ready for it.

The question is actually: Why was it not ready? My guess would be that an error came up momentarily with one of the clustered workers and should be shown in the output (or viewable via Chrome's Network tab in Inspect Element).

**Comment by uaktags** [comment]
No response.
