### ISSUE TITLE
Running but cannot see the page in the browser - Unable to connect

### ISSUE THREAD

**Issue by ghost** [iquidus/explorer#490]
Just putting this up here for anyone trying to work out why everything seems to be running OK but in Firefox you cannot open 127.0.0.1 as you get an 'Unable to connect' error - An error occurred during a connection to 127.0.0.1

This is a Firefox issue, not an problem with this Git, Chromium will open the page just fine.

**Comment by joeuhren** [comment]
Thanks for the tip, but just so you and everyone else reading this knows, this is obviously something unique to your own setup since firefox has absolutely no problem viewing the explorer in any way.

![image](https://user-images.githubusercontent.com/46763106/170152752-a1c66d69-c593-4051-9e58-b258d6e085a1.png)

**Comment by joeuhren** [comment]
I just realized I should have shown the loopback address (127.0.01) instead of internal Ip in case anyone wants to think that matters:
![image](https://user-images.githubusercontent.com/46763106/170152986-3421753c-ea19-413e-a07a-eec80f1f76f4.png)

**Comment by uaktags** [comment]
Closing as unrelated to the git, please reply with a screenshot or more information as to the issue.

If you're getting ``'Unable to connect' error - An error occurred during a connection to 127.0.0.1`` then it sounds like you're connecting to http://127.0.0.1 (port 80) and not http://127.0.0.1:3001 (port 3001 explicitly).
