### ISSUE TITLE
i cant make a crontab that will actually work/update index.

### ISSUE THREAD

**Issue by modestcoin** [iquidus/explorer#512]
explorer is working perfect, i can manually index, but the crontab -e im creating, EX. (
*/1 * * * * cd /root/explorer && /usr/bin/nodejs scripts/sync.js index update > /dev/null 2>&1
*/2 * * * * cd /root/explorer && /usr/bin/nodejs scripts/sync.js market > /dev/null 2>&1
*/5 * * * * cd /root/explorer && /usr/bin/nodejs scripts/peers.js > /dev/null 2>&1 )

will not work, i'm not understanding because there is no "usr/bin/nodejs scripts/sync.js" in my server, there located in explorer/scripts, so is the command even calling the script to run or what could be going wrong,,, thanks

**Comment by uaktags** [comment]
Do a "whereis node" to get the location of your node. 

Then update accordingly.

**Comment by modestcoin** [comment]
sorry im feeling a bit dense, said command returned "/root/.nvm/versions/node/v12.14.0/bin/node"
what am i suppose to be updating? i checked the bin folder of said path, and there is no "nodejs scripts" or anything like that.

**Comment by uaktags** [comment]
So the crontab is running 3 sets of commands at the intervals specified.

What they're doing is cd'ing into wherever you installed the explorer. In our readme that is /root/explorer as an example. Update this to whatever path you installed inquidis on your server if it's different.

The second part (after &&) is running the nodejs command (which in our readme is installed to /use/bin/nodejs) with the argument "scripts/..." this scripts folder is located in the folder of the explorer (which we just cd' into).

So for you, update the crontab to update the path for the explorer (if it's different) and change "/usr/bin/nodejs" to be the path you got from there whereis.

**Comment by modestcoin** [comment]
that made things 110% understandable for me, thank you so much! it now works

**Comment by uaktags** [comment]
Glad to hear it! I'm pretty sure there's one more thing with nvm (just noticed you refenced that) so that you could call it from /bin or something of the sort, but unfortunately i'm on a train and can't find it quickly.

I'm going to close this issue, but once i get to my hotel i'll check into that and see what you're missing. I hate the idea of having such a large path for node in the crontab, when the purpose of nvm is to allow you easily upgrade/change your node versions. So we wouldn't want to have to update the crontab just because of a version update.
